planning_3d_prm:
  ros__parameters:
    pcd_path: /workspace/Nav_3d/src/data/traversable_cloud/traversable_areas.pcd
    map_frame: map
    robot_frame: base_link
    edt_xy_expand: 1.0
    edt_z_thickness: 3
    robot_height: 1.0
    enable_headroom_check: true
    safe_margin: 0.4
    voxel_leaf: 0.4
    use_clearance_penalty: true
    clearance_penalty_weight: 22750.0
    clearance_penalty_scale: 0.3
    use_soft_penalty: false
    step_size: 1.0
    max_nodes: 10000
    k_neigh: 50
    max_slope_deg: 45.0
    auto_replan: true
    replan_frequency: 1.0
    pos_tolerance: 0.5
    pos_tolerance_exit: 2.0
    yaw_tolerance: 0.14
    obstacle_block_radius: 0.0
    obstacle_timeout: 5.0
    random_seed: 42
