ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}-ros-base AS nav3d-deps

ARG ROS_DISTRO
ARG CASADI_VERSION=3.6.7
ARG BUILD_JOBS=4
ENV DEBIAN_FRONTEND=noninteractive \
    ROS_DISTRO=${ROS_DISTRO} \
    NAV3D_WS=/opt/nav3d_ws \
    NAV3D_DATA_ROOT=/data \
    CASADI_ROOT=/opt/casadi \
    CASADI_LIB_PATH=/opt/casadi/lib

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git ninja-build pkg-config python3-pip python3-rosdep \
    libapr1-dev libboost-all-dev libeigen3-dev libgoogle-glog-dev libnanoflann-dev \
    libopen3d-dev libpcl-dev libpcap-dev libtbb-dev libyaml-cpp-dev \
    coinor-libipopt-dev liblapack-dev gfortran \
    ros-${ROS_DISTRO}-ament-cmake-auto ros-${ROS_DISTRO}-ament-cmake-python \
    ros-${ROS_DISTRO}-pcl-conversions ros-${ROS_DISTRO}-tf2-ros \
    ros-${ROS_DISTRO}-tf2-geometry-msgs ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-rosbag2 && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch ${CASADI_VERSION} https://github.com/casadi/casadi.git /tmp/casadi && \
    cmake -S /tmp/casadi -B /tmp/casadi/build -GNinja \
      -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CASADI_ROOT} \
      -DWITH_IPOPT=ON -DWITH_PYTHON=OFF -DWITH_EXAMPLES=OFF && \
    cmake --build /tmp/casadi/build --parallel ${BUILD_JOBS} && \
    cmake --install /tmp/casadi/build && rm -rf /tmp/casadi

RUN git clone --depth 1 https://github.com/Livox-SDK/Livox-SDK2.git /tmp/livox-sdk2 && \
    cmake -S /tmp/livox-sdk2 -B /tmp/livox-sdk2/build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build /tmp/livox-sdk2/build --parallel ${BUILD_JOBS} && \
    cmake --install /tmp/livox-sdk2/build && rm -rf /tmp/livox-sdk2 && ldconfig

FROM nav3d-deps AS nav3d-runtime
ARG ROS_DISTRO
WORKDIR ${NAV3D_WS}
COPY src/3D_NAV src
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    apt-get update && rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO} && \
    rm -rf /var/lib/apt/lists/* && \
    colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Release

COPY docker/entrypoint.ros2.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && mkdir -p /data
ENV LD_LIBRARY_PATH=/opt/casadi/lib:/usr/local/lib
ENTRYPOINT ["/entrypoint.sh"]
CMD ["ros2", "launch", "nav_bringup", "full_stack.launch.py"]
