<?xml version="1.0"?>
<package format="3">
  <name>nav_bringup</name>
  <version>2.0.0</version>
  <description>Native ROS 2 mapping, localization and 3D navigation launch system.</description>
  <maintainer email="2721705912@qq.com">Chen-lvping</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>fast_lio</exec_depend>
  <exec_depend>open3d_loc</exec_depend>
  <exec_depend>planning_3d</exec_depend>
  <exec_depend>bezier_path_optimizer</exec_depend>
  <exec_depend>nmpc_planner</exec_depend>
  <exec_depend>obstacle_processor</exec_depend>
  <exec_depend>map_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
