<?xml version="1.0"?>
<package format="3">
  <name>rslidar_sdk</name>
  <version>1.5.16</version>
  <description>Native ROS 2 RoboSense LiDAR SDK node.</description>
  <maintainer email="support@robosense.cn">RoboSense</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rslidar_msg</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>libpcap</depend>
  <depend>yaml-cpp</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
