cmake_minimum_required(VERSION 3.8)
project(pcd_down_sample)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(nav3d_ros2_compat REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(pcl_conversions REQUIRED)
find_package(PCL REQUIRED COMPONENTS common io filters)
add_executable(pcd_down_sample_rotate src/pcd_down_sample_rotate.cpp)
target_include_directories(pcd_down_sample_rotate PRIVATE ${PCL_INCLUDE_DIRS})
target_link_libraries(pcd_down_sample_rotate ${PCL_LIBRARIES})
ament_target_dependencies(pcd_down_sample_rotate
  nav3d_ros2_compat rclcpp sensor_msgs pcl_conversions)
install(TARGETS pcd_down_sample_rotate DESTINATION lib/${PROJECT_NAME})
ament_package()
